USE master;
GO 
IF EXISTS(SELECT 1 FROM SYS.databases WHERE NAME='DataWareHouse')
BEGIN
  ALTER DATABASE DataWareHouse SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
  DROP DATABASE DataWareHouse;
END ;
GO 


--CREATE THE DataWareHouse DATABASE 
CREATE DATABASE DataWareHouse;
GO


USE DataWareHouse;
GO


--CREATE SCHEMAS
CREATE SCHEMA bronze;
GO 
CREATE SCHEMA silver;
GO 
CREATE SCHEMA gold;

